texto = input("Ingrese texto: ").lower()
letra_1 = input("Ingrese la primera letra: ").lower()
letra_2 = input("Ingrese la segunda letra: ").lower()
letra_3 = input("Ingrese la tercera letra: ").lower()
lista = [letra_1,letra_2,letra_3]
#print(texto)
#print(lista)
print(f"la letra {letra_1}: aparece {texto.count(lista[0])} veces en el texto")
print(f"la letra {letra_2}: aparece {texto.count(lista[1])} veces en el texto")
print(f"la letra {letra_3}: aparece {texto.count(lista[2])} veces en el texto")
texto_lista = texto.split(" ")
print(f"El texto tiene {len(texto_lista)} palabras")
print(f"la primera letra: {texto[0]}")
print(f"la última letra: {texto[-1]}")
print(" ".join(texto_lista[::-1]))
resultado = {True:"sí",False:"no"}
print(f'La plabra python aparece en el texto? {resultado["python" in texto.lower()]}')